{% set name = "gruut-lang-en" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gruut_lang_en-{{ version }}.tar.gz
  sha256: a3d748bca5b31bf89d26b00ba76809532187696ce3ddf76b35889fe25f94ea30

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - gruut_lang_en
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rhasspy/gruut
  dev_url: https://github.com/rhasspy/gruut/tree/master/gruut-lang-en
  summary: English language files for gruut tokenizer/phonemizer
  license: MIT
  # LICENSE currently manually packaged in for this "sub package" upstream
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
